import os
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv

def send_error_email(script_name, error_message):
    load_dotenv(".envrc.dev")
    my_email = os.getenv("GMAIL_EMAIL")
    my_email_app_passowrd = os.getenv("GMAIL_APP_PASSWORD")
    should_send_email = os.getenv("SHOULD_SEND_EMAIL")
    if should_send_email:
            msg = EmailMessage()
            msg.set_content(
                f"Your script: '{script_name}' failed with the following error:\n\n"
                f"{error_message}\n\n"
                f"---\n"
                f"This message was autogenerated by the server 🤖"
            )
            msg["Subject"] = f"⚠️ - Script {script_name} has failed"
            msg["From"] = my_email
            msg["To"] = my_email

            # Example using Gmail's SMTP server
            try:
                with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
                    server.login(my_email, my_email_app_passowrd)
                    server.send_message(msg)
            except Exception as e:
                print(f"Failed to send email: {e}")
    else:
        print("Skip sending email")

# send_error_email("my_script.py", "some long error for test")